-- MySQL Script generated by MySQL Workbench
-- Sun Dec  6 14:17:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema campus_eats_fall2020
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema campus_eats_fall2020
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `campus_eats_fall2020` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`person` (
  `person_id` INT(11) NOT NULL AUTO_INCREMENT,
  `person_name` VARCHAR(300) NULL DEFAULT NULL,
  `person_email` VARCHAR(150) NULL DEFAULT NULL,
  `cell` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 206
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`student` (
  `student_id` INT(11) NOT NULL AUTO_INCREMENT,
  `person_id` INT(11) NOT NULL,
  `graduation_year` INT(4) NULL DEFAULT NULL,
  `major` VARCHAR(75) NULL DEFAULT NULL,
  `type` VARCHAR(75) NULL DEFAULT NULL,
  PRIMARY KEY (`student_id`),
  INDEX `fk_St_person_id` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_St_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `campus_eats_fall2020`.`person` (`person_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 152
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`driver` (
  `driver_id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NOT NULL,
  `license_number` VARCHAR(75) NULL DEFAULT NULL,
  `date_hired` DATE NULL DEFAULT NULL,
  `rating` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`driver_id`),
  INDEX `fk_D_student_id` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_D_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `campus_eats_fall2020`.`student` (`student_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`vehicle` (
  `vehicle_id` INT(11) NOT NULL AUTO_INCREMENT,
  `vehicle_plate` VARCHAR(75) NULL DEFAULT NULL,
  `model` VARCHAR(75) NULL DEFAULT NULL,
  `make` VARCHAR(75) NULL DEFAULT NULL,
  PRIMARY KEY (`vehicle_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`delivery` (
  `delivery_id` INT(11) NOT NULL AUTO_INCREMENT,
  `driver_id` INT(11) NOT NULL,
  `vehicle_id` INT(11) NOT NULL,
  `delivery_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`delivery_id`),
  INDEX `fk_delivery_driver_id` (`driver_id` ASC) VISIBLE,
  INDEX `fk_delivery_vehicle_id` (`vehicle_id` ASC) VISIBLE,
  CONSTRAINT `fk_delivery_driver_id`
    FOREIGN KEY (`driver_id`)
    REFERENCES `campus_eats_fall2020`.`driver` (`driver_id`),
  CONSTRAINT `fk_delivery_vehicle_id`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `campus_eats_fall2020`.`vehicle` (`vehicle_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`location` (
  `location_id` INT(11) NOT NULL AUTO_INCREMENT,
  `location_name` VARCHAR(75) NULL DEFAULT NULL,
  `location_address` VARCHAR(75) NULL DEFAULT NULL,
  `latitude` VARCHAR(75) NULL DEFAULT NULL,
  `longitude` VARCHAR(75) NULL DEFAULT NULL,
  `drop_off_point` VARCHAR(75) NULL DEFAULT NULL,
  PRIMARY KEY (`location_id`),
  UNIQUE INDEX `location_index_desc` (`location_id` ASC) VISIBLE,
  INDEX `idx_location_location_name` (`location_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`restaurant` (
  `restaurant_id` INT(11) NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(75) NULL DEFAULT NULL,
  `restaurant_name` VARCHAR(75) NULL DEFAULT NULL,
  `schedule` VARCHAR(75) NULL DEFAULT NULL,
  `website` VARCHAR(75) NULL DEFAULT NULL,
  PRIMARY KEY (`restaurant_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`order` (
  `order_id` INT(11) NOT NULL AUTO_INCREMENT,
  `person_id` INT(11) NOT NULL,
  `delivery_id` INT(11) NOT NULL,
  `location_id` INT(11) NOT NULL,
  `driver_id` INT(11) NOT NULL,
  `restaurant_id` INT(11) NOT NULL,
  `total_price` FLOAT NOT NULL,
  `delivery_charge` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_O_person_id` (`person_id` ASC) VISIBLE,
  INDEX `fk_O_delivery_id` (`delivery_id` ASC) VISIBLE,
  INDEX `fk_O_location_id` (`location_id` ASC) VISIBLE,
  INDEX `fk_O_driver_id` (`driver_id` ASC) VISIBLE,
  INDEX `fk_O_restaurant_id` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_O_delivery_id`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `campus_eats_fall2020`.`delivery` (`delivery_id`),
  CONSTRAINT `fk_O_driver_id`
    FOREIGN KEY (`driver_id`)
    REFERENCES `campus_eats_fall2020`.`driver` (`driver_id`),
  CONSTRAINT `fk_O_location_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `campus_eats_fall2020`.`location` (`location_id`),
  CONSTRAINT `fk_O_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `campus_eats_fall2020`.`person` (`person_id`),
  CONSTRAINT `fk_O_restaurant_id`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `campus_eats_fall2020`.`restaurant` (`restaurant_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rating` (
  `rating_id` INT(11) NOT NULL,
  `person_id` INT(11) NOT NULL,
  `order_id` INT(11) NOT NULL,
  `rating_num` INT(1) NULL,
  `rating_desc` VARCHAR(1000) NULL,
  `rating_time` TIMESTAMP NULL DEFAULT DATE_TIME,
  PRIMARY KEY (`rating_id`),
  INDEX `person_id_idx` (`person_id` ASC) VISIBLE,
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `campus_eats_fall2020`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `campus_eats_fall2020`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

USE `campus_eats_fall2020` ;

-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`faculty` (
  `faculty_id` INT(11) NOT NULL AUTO_INCREMENT,
  `person_id` INT(11) NOT NULL,
  `title` VARCHAR(75) NULL DEFAULT NULL,
  `degree_college` VARCHAR(75) NULL DEFAULT NULL,
  `highest_degree` VARCHAR(75) NULL DEFAULT NULL,
  PRIMARY KEY (`faculty_id`),
  INDEX `fk_F_person_id` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_F_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `campus_eats_fall2020`.`person` (`person_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `campus_eats_fall2020`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`staff` (
  `staff_id` INT(11) NOT NULL AUTO_INCREMENT,
  `person_id` INT(11) NULL DEFAULT NULL,
  `position` VARCHAR(75) NULL DEFAULT NULL,
  `is_admin` VARCHAR(1) NULL DEFAULT 'N',
  PRIMARY KEY (`staff_id`),
  INDEX `fk_S_person_id` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_S_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `campus_eats_fall2020`.`person` (`person_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = latin1;

USE `campus_eats_fall2020` ;

-- -----------------------------------------------------
-- Placeholder table for view `campus_eats_fall2020`.`person_join`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`person_join` (`person_id` INT, `person_name` INT, `person_email` INT, `student_id` INT, `graduation_year` INT);

-- -----------------------------------------------------
-- Placeholder table for view `campus_eats_fall2020`.`person_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campus_eats_fall2020`.`person_student` (`person_id` INT, `person_name` INT, `person_email` INT, `cell` INT);

-- -----------------------------------------------------
-- View `campus_eats_fall2020`.`person_join`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campus_eats_fall2020`.`person_join`;
USE `campus_eats_fall2020`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `campus_eats_fall2020`.`person_join` AS select `campus_eats_fall2020`.`person`.`person_id` AS `person_id`,`campus_eats_fall2020`.`person`.`person_name` AS `person_name`,`campus_eats_fall2020`.`person`.`person_email` AS `person_email`,`campus_eats_fall2020`.`student`.`student_id` AS `student_id`,`campus_eats_fall2020`.`student`.`graduation_year` AS `graduation_year` from (`campus_eats_fall2020`.`person` join `campus_eats_fall2020`.`student` on((`campus_eats_fall2020`.`student`.`person_id` = `campus_eats_fall2020`.`person`.`person_id`))) where (`campus_eats_fall2020`.`student`.`major` = 'Computer Science');

-- -----------------------------------------------------
-- View `campus_eats_fall2020`.`person_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `campus_eats_fall2020`.`person_student`;
USE `campus_eats_fall2020`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `campus_eats_fall2020`.`person_student` AS select `a`.`person_id` AS `person_id`,`a`.`person_name` AS `person_name`,`a`.`person_email` AS `person_email`,`a`.`cell` AS `cell` from `campus_eats_fall2020`.`person` `a` where `a`.`person_id` in (select `campus_eats_fall2020`.`student`.`person_id` from `campus_eats_fall2020`.`student` where (`campus_eats_fall2020`.`student`.`graduation_year` = 2019));
USE `mydb`;

DELIMITER $$
USE `campus_eats_fall2020`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `campus_eats_fall2020`.`order_AFTER_INSERT`
AFTER INSERT ON `campus_eats_fall2020`.`order`
FOR EACH ROW
BEGIN
	insert into niner_eats.delivery (driver_id, vehicle_id) values(new.driver_id, 2);
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
